version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_transcendence
      POSTGRES_USER: ft_user
      POSTGRES_PASSWORD: ft_passw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
      build:
        context: ./pong
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./pong:/code
      ports:
        - "8000:8000"
      depends_on:
        - db

volumes:
  postgres_data:
