
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5422:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  web:
      build:
        context: ./pong
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./pong:/code
      env_file:
        - .env
      environment:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      ports:
        - "4222:8000"
      depends_on:
        - db
        - redis
      restart: "always"

  redis:
    image: redis:5
    restart: "always"

volumes:
  postgres_data:
