#version: '42'

networks:
  transcendeNet:
    driver: bridge

services:
  # blockchain:
  #   image: trufflesuite/ganache
  #   environment:
  #     - INFURA_TESTNET
  #   networks:
  #     - transcendeNet
  #   ports:
  #     - "8545:8545"
  #   restart: unless-stopped
  db:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - "${PWD}/postgres_data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transcendeNet
    restart: unless-stopped

  redis:
    image: redis:7.2.5-alpine
    networks:
      - transcendeNet
    restart: unless-stopped

  django:
    build:
      context: "${PWD}/pong"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "${PWD}/pong:/code:rw"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI
    ports:
      - "4222:8000"
    networks:
      - transcendeNet
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - transcendeNet
    ports:
      - "4444:4444"
      - "5900:5900"  # VNC port
    restart: unless-stopped
    profiles:
      - debug

  novnc:
    image: javanile/novnc
    environment:
      - REMOTE_HOST=localhost
      - REMOTE_PORT=5901
    ports:
      - 8081:8081
    links:
      - selenium
    profiles:
      - debug
    networks:
      - transcendeNet
