POST https://wow.transcend42.online/api/register/
Content-Type: application/json

{ "username": "foo", "password": "foo", "password_confirmation": "foo", "email": "foo@foo.com" }

###

POST https://wow.transcend42.online/api/login/
Content-Type: application/json

{ "username": "foo", "password": "foo" }

###

POST https://wow.transcend42.online/api/token/refresh/
Content-Type: application/json
Authorization: Bearer 

{ "refresh": "" }

###

POST https://wow.transcend42.online/api/logout/
Content-Type: application/json
Authorization: Bearer 

{ }

###
